import{a as v,S,i as a}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="56799357-5764c9f004e69503c7bfa7d57",E="https://pixabay.com/api/";async function g(r,t=1){const{data:i}=await v.get(E,{params:{key:q,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return i}const P=new S(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".gallery"),u=document.querySelector(".loader"),p=document.querySelector(".load-more");function m(r){const t=r.map(({webformatURL:i,largeImageURL:l,tags:e,likes:o,views:n,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${i}" alt="${e}" />
        </a>
        <div class="gallery-caption">
          <ul class="gallery-caption-list">
            <li class="gallery-caption-item"><span class="caption-label">Likes</span><span>${o}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Views</span><span>${n}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Comments</span><span>${b}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Downloads</span><span>${w}</span></li>
          </ul>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){h.innerHTML=""}function f(){u&&u.classList.add("active")}function d(){u&&u.classList.remove("active")}function y(){p&&p.classList.add("hidden")}function L(){p&&p.classList.remove("hidden")}const B=document.querySelector(".form"),$=document.querySelector(".load-more");let s=1,c="";B.addEventListener("submit",async r=>{if(y(),s=1,r.preventDefault(),c=r.target.elements["search-text"].value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}R(),f();try{const t=await g(c,s);if(d(),!t.hits||t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),t.totalHits>s*15?L():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error(t),a.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),d()}r.target.reset()});$.addEventListener("click",async()=>{s++,y(),f();try{const r=await g(c,s);if(d(),!r.hits||r.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(r.hits);const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),r.totalHits>s*15?L():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(r){console.error(r),a.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),d()}});
//# sourceMappingURL=index.js.map
