import{a as b,S as v,i as s}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const w="56799357-5764c9f004e69503c7bfa7d57",E="https://pixabay.com/api/";function u(r,t=1){return b.get(E,{params:{key:w,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const S=new v(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),d=document.querySelector(".loader");function h(r){const t=r.map(({webformatURL:o,largeImageURL:c,tags:e,likes:a,views:n,comments:f,downloads:L})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${o}" alt="${e}" />
        </a>
        <div class="gallery-caption">
          <ul class="gallery-caption-list">
            <li class="gallery-caption-item"><span class="caption-label">Likes</span><span>${a}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Views</span><span>${n}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Comments</span><span>${f}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Downloads</span><span>${L}</span></li>
          </ul>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){g.innerHTML=""}function m(){d&&d.classList.add("active")}function y(){d&&d.classList.remove("active")}const P=document.querySelector(".form"),l=document.querySelector(".load-more");let i=1,p="";P.addEventListener("submit",async r=>{if(l.classList.add("hidden"),i=1,r.preventDefault(),p=r.target.elements["search-text"].value.trim(),!p){s.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}q(),m();try{const t=await u(p,i);if(!t.hits||t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),t.totalHits>i*15?l.classList.remove("hidden"):s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error(t),s.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}y(),r.target.reset()});l.addEventListener("click",async()=>{i++,l.classList.add("hidden"),m();try{const r=await u(p,i);if(!r.hits||r.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(r.hits);const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),r.totalHits>i*15?l.classList.remove("hidden"):s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(r){console.error(r),s.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}y()});
//# sourceMappingURL=index.js.map
